
# show_downloads: false
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
  parse_block_html: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "home"

title:            'AdvancedSolver Cluster Guide Page'
tagline:          'Guide Page'
description:      'From just-the-docs template.'
url:              http://example.com
baseurl:          /
github:
  repo:           https://github.com/AdvancedSolverCluster/advancedsolvercluster.github.io/
logo: "/assets/images/logo/cash-logo.png"
favicon_ico: "/assets/images/logo/favicon/favicon-32x32.ico"

theme: just-the-docs

url: https://advancedsolvercluster.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from